### PR TITLE
[RFC] Add early environment variable resolution to fusesoc

### PR DESCRIPTION
**Pull request by Jbalkind**
Adds a --resolve-env-vars-early flag to FuseSoC which allows for environment variables in core files. These are resolved in FuseSoC rather than edalize. I imagine we could add a --resolve-env-vars-late (or make this into a flag with an argument) to enable resolution in edalize for use cases that need that.

### CODE REVIEW

**Comment by olofk** [comment]
This is fine with me. It looks like macosx tests are broken though. Could it be that mkdir is not in /usr/bin on macosx? If so, do we really need to specify an absolute path?

**Comment by olofk** [comment]
Ah! I understand now that all tests were broken prior to this. Looking at the tox docs, it seems perfectly fine to just allowlist the command without an absolute path, so could you please amend your patch to remove `/usr/bin/' to make tests work again on MacOSX as well?

**Comment by Jbalkind** [comment]
Ok between that and pulling in your opencores patch, the CI passes. I can juggle those commits around in some other way or you can handle it since I know you don't like merges.

**Comment by olofk** [comment]
Many thanks! All good from my side. I can do the cherry-picking.

**Comment by olofk** [comment]
Picked and pushed! All back to green. Thanks

**Pull request closed without merging**
