### PR TITLE
Pathlib migration

### PR DESCRIPTION
**Pull request by dominicdoty**
Now that the minimum Python required version has moved up to 3.6, pathlib migration should be possible.

Addresses:
#376  #458

### CODE REVIEW

**Comment by imphil** [comment]
Hi @dominicdoty, thanks for your pull request! It's a good start, but will need a bit more work to pass our CI tests.

I'd recommend running the tests locally as documented at https://fusesoc.readthedocs.io/en/latest/dev/devsetup.html#running-tests to see where the failures come from.

If you have problems understanding the failures, with GitHub, or anything of that sort, please reach out and we can help you through it.

**Comment by dominicdoty** [comment]
Apologies, I was a bit premature in my pull request, didn't realize it would show up and run tests while still a draft :grimacing: 

I'm working my way through the rest of the files in the repo over the next few days.

**Comment by imphil** [comment]
Don't worry and no hurry! I only wanted to make sure we're on the same page and not both wait for the other person to act :smile:

**Comment by olofk** [comment]
This wasn't intended to be closed. It happened when I renamed the default branch. Please reopen if it's still relevant

**Pull request closed without merging**
