### PR TITLE
Add support for real generics/parameters

### PR DESCRIPTION
**Pull request by GCHQDeveloper560**
#383

### CODE REVIEW

**Comment by olofk** [comment]
Hold on... can we really pull this off without _any_ changes in Edalize? Looking at the code it really seems like it would work. I'm just surprised because it was never my intention to make that possible :)

Anyway, if it works, let's go with it and just make a small update in the EDAM documentation to mention the existence of the real type. I have a slight preference for calling these float instead of real, but I don't care all that much.

So, if you could just confirm that there are no corresponding Edalize changes that I need to apply first, and I'll merge this

**Comment by DHWinterWolf** [comment]
I've run a few tests on this branch, and can confirm it works fine with current Edalize at master, at least as far as ModelSim is concerned.

**Comment by DHWinterWolf** [comment]
And for what it's worth, float would be fine by me if there's a preference for that name.

**Comment by olofk** [comment]
Thanks. Let's push this and keep it real! :)

**Pull request merged**
