### PR TITLE
Allow + characters in parsed expressions

### PR DESCRIPTION
**Pull request by sjalloq**
- added "+" to the list of special characters allowed in the parser.

### CODE REVIEW

**Comment by imphil** [comment]
Thanks for your pull request. Can you describe what code triggered the need for this change?

**Comment by sjalloq** [comment]
Hi Phil,

a certain incumbent with an area optimised CPU has directory names with a "+" in them.

Shareef.

**Comment by imphil** [comment]
I see, thanks! I had a closer look and we need to think a bit more about the "word" definition in here, since theoretically any valid path name should be allowed (effectively any character). (And add tests for it.) But for now let's unblock your work and get this merged.

As a minimal change, would you mind updating the grammar definition in line 15 of the exprs.py file as well?

And there seems to be a mismatch between the grammar and the implementation with "~" appearing twice in the implementation. Can you align the two as well? (The additional backslash escaping in the grammar is intentional.)

CC @rswarbrick

**Comment by sjalloq** [comment]
Thanks for the update.  I'll take a look at this sometime this week.

**Comment by rswarbrick** [comment]
This looks good to me. As Philipp said, could you update the comment at the top? Also, please could you add a line to `test_exprs.py` with a plus in it? Maybe something like
```python
    check_parses_to("a+b", ["a+b"])
```
as the second line in `test_exprs`?

@imphil: I don't think we can allow arbitrary valid paths here. After all, they can contain things like spaces and newlines, which isn't going to play well with the rest of the syntax!

**Comment by imphil** [comment]
> @imphil: I don't think we can allow arbitrary valid paths here. After all, they can contain things like spaces and newlines, which isn't going to play well with the rest of the syntax!
Merge state

Yeah, not sure if the current syntax is actually able to cover all edge cases. That's why I pushed it out into the "let's think about it some other day" area.

**Comment by rswarbrick** [comment]
Yep, sounds sensible. I guess that if we want to handle arbitrary paths, we should allow an "escaped" syntax. Maybe allow a word to be a C-style string or something? But it's quite a bit more complexity, and I'm not sure it's really worth the effort.

**Comment by sjalloq** [comment]
Think I've covered all the requests here.

**Comment by imphil** [comment]
Thanks for your contribution! I combined the two commits into one and merged them.

**Pull request merged**
